import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

import useWindowSize from "react-use/lib/useWindowSize";
import Confetti from "react-confetti";

export default function Home() {
  const { width, height } = useWindowSize();

  return (
    <>
      <Head>
        <title>Quyens Birthday</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Confetti width={width} height={height} />
      <div style={{ textAlign: "center", margin: "auto", fontSize: 50 }}>
        Happy Birthday Quyen!
      </div>
    </>
  );
}
